deploy_staging:
  type: deploy
  environment:
    name: staging
    url: moim.id
  script:
    - ssh dev@178.128.21.74 "cd var/www/html/moim-git && git checkout master && git pull origin master && exit"
  only:
    - master
