    - action: "[178.128.21.74] Execute: git pull origin master"
      type: "SSH_COMMAND"
      working_directory: "/var/www/html/moim-git"
      login: "dev"
      password: "K9tC9bmY"
      host: "178.128.21.74"
      port: "22"
      authentication_mode: "PASS"
      ignore_errors: true
      shell: "SH"
      run_as_script: true
      commands:
      - "cd /var/www/html/moim-git"
      - "git pull origin master"
      - "composer update --silent"
